spring:
  config:
    import: optional:classpath:secret-application.yml
  graphql:
    graphiql:
      enabled: true
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:3000
  data:
    mongodb:
      uri: mongodb://localhost:27017/visitor-entry-pass
      database: VisitorEntryPass
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

#folder:
#  images: ""
#
#telegram:
#  bot:
#    username: ""
#    token: ""
#  chatIdSuryansh: ""